# Generated by Django 4.1.3 on 2023-12-06 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunaapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='age',
        ),
    ]
