# Generated by Django 4.1.3 on 2023-12-06 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunaapi', '0002_remove_artist_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='age',
            field=models.IntegerField(default=20, max_length=50),
            preserve_default=False,
        ),
    ]
